[project]
name = "deeplearning2"
version = "0.1.0"
description = "Deep Learning From Scratch 2"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
]
